#!/bin/bash
python3 train.py --train-ds-path train/data/path \
                 --val-ds-path val/data/path \
                 --input_size 224 \
                 --normalize_mean 0.485 0.456 0.406 \
                 --normalize_std 0.229 0.224 0.225 \
                 --aug_strength weak \
                 --batch_size 8 \
                 --ema \
                 --optimizer adamw \
                 --learning_rate 0.0001 \
                 --dropout 0.2 \
                 --freeze_bottom \
                 --arch efficientnet_b1 \
                 --smoothing 0.0 \
                 --epochs 50 \
                 --seed 42 \
                 --ckpt-path weights/ \
                 --log-path logs/ \
                 --device 0 \
                 --n-worker 4
