#!/bin/bash
python3 train.py --clearml-project minhnq54/fraud-id-clf \
                 --clearml-task 'Fraud ID number detection' \
                 --train-ds-name id-field-train \
                 --train-ds-ver 1.0.3 \
                 --val-ds-name id-field-val \
                 --val-ds-ver 1.0.0 \
                 --input_size 32 240 \
                 --normalize_mean 0.627 0.586 0.536 \
                 --normalize_std 0.237 0.221 0.214 \
                 --aug_strength weak \
                 --batch_size 128 \
                 --optimizer adamw \
                 --learning_rate 0.01 \
                 --dropout 0.2 \
                 --freeze_bottom \
                 --arch efficientnet_b1 \
                 --smoothing 0.4 \
                 --epochs 200 \
                 --seed 42 \
                 --ckpt-path weights/id-number-exp \
                 --device 0 \
                 --n-worker 4
